
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ProductController;
import controller.TransaksiController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.product;
import model.userSession;

/**
 *
 * @author Santa
 */
public class FormKasir extends javax.swing.JFrame {
        ProductController prodCtrl = new ProductController();
        TransaksiController transCtrl = new TransaksiController();
        DefaultTableModel model;
        int totalBelanja = 0;
    /**
     * Creates new form FormKasir
     */
    private void resetForm() {
    
    model.setRowCount(0); 
    totalBelanja = 0;
    jLabel7.setText("0"); 
    
    
    kodeBarang.setText("");
    namaBarang.setText("");
    kuantitas.setText("");
    bayar.setText("");
    kembalian.setText("");
    pelanggan.setText(""); 
    tglTransaksi.setDate(new java.util.Date());
    selesai.setEnabled(false); 
    
    
    noTransaksi.setText(transCtrl.getNoTransaksiOtomatis());
    pelanggan.setText("1");
    
    kodeBarang.requestFocus();
}
    public FormKasir() {
        initComponents();
        this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        String nama = userSession.getNama_pegawai();
        namaKasir.setText(nama);
        model = new DefaultTableModel();
        table.setModel(model);
        model.addColumn("ID Product");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Qty");
        model.addColumn("Subtotal");

        
        tglTransaksi.setDate(new Date());

    
        namaBarang.setEditable(false);
        controller.TransaksiController trans = new controller.TransaksiController();
        String noBaru = trans.getNoTransaksiOtomatis();
    
    
        noTransaksi.setText(noBaru);
    
    
        noTransaksi.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        namaKasir = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        inventory = new javax.swing.JButton();
        generateLaporan = new javax.swing.JButton();
        akhirHari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tanggal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        noTransaksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pelanggan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kodeBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        namaBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kuantitas = new javax.swing.JTextField();
        tambahkan = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        proses = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tglTransaksi = new com.toedter.calendar.JDateChooser();
        delete = new javax.swing.JButton();
        selesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setText("Kasir");

        namaKasir.setEditable(false);
        namaKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKasirActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        inventory.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        inventory.setText("Inventory");
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });

        generateLaporan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        generateLaporan.setText("Generate Laporan");
        generateLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateLaporanActionPerformed(evt);
            }
        });

        akhirHari.setBackground(new java.awt.Color(102, 0, 0));
        akhirHari.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        akhirHari.setForeground(new java.awt.Color(255, 255, 255));
        akhirHari.setText("End Day");
        akhirHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akhirHariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generateLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(akhirHari, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(akhirHari)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 685, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        table.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Qty", "Sub total", "Option"
            }
        ));
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel1.setText("No Transaksi");

        noTransaksi.setEditable(false);
        noTransaksi.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        noTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTransaksiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel2.setText("ID Pelanggan");

        pelanggan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setText("Tanggal");

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel4.setText("Kode Barang");

        kodeBarang.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        kodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeBarangActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel5.setText("Nama Barang");

        namaBarang.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        namaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setText("Qty");

        kuantitas.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        kuantitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuantitasActionPerformed(evt);
            }
        });

        tambahkan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tambahkan.setText("Tambahkan");
        tambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkanActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        proses.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setText("Bayar");

        bayar.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setText("Kembalian");

        kembalian.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tanggalLayout = new javax.swing.GroupLayout(tanggal);
        tanggal.setLayout(tanggalLayout);
        tanggalLayout.setHorizontalGroup(
            tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tanggalLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noTransaksi))
                    .addGroup(tanggalLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tanggalLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(71, 71, 71)
                .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tanggalLayout.createSequentialGroup()
                        .addComponent(kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(50, 50, 50)
                .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tanggalLayout.createSequentialGroup()
                        .addComponent(tambahkan)
                        .addGap(18, 18, 18)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proses, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tanggalLayout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tanggalLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(19, 19, 19)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
        );
        tanggalLayout.setVerticalGroup(
            tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalLayout.createSequentialGroup()
                .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tanggalLayout.createSequentialGroup()
                        .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tanggalLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(noTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tanggalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tanggalLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tanggalLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel2))))
                            .addGroup(tanggalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(12, 12, 12)
                        .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tambahkan)
                            .addComponent(reset)
                            .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(proses)
                                .addComponent(delete))
                            .addComponent(tglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tanggalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(tanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap())
        );

        selesai.setBackground(new java.awt.Color(0, 102, 51));
        selesai.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        selesai.setForeground(new java.awt.Color(255, 255, 255));
        selesai.setText("Selesai");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTransaksiActionPerformed

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelangganActionPerformed

    private void kodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeBarangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_kodeBarangActionPerformed

    private void namaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBarangActionPerformed

    private void kuantitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuantitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kuantitasActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        try {
        
        if (totalBelanja == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Keranjang Kosong!");
            return;
        }

        
        if (bayar.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan jumlah uang bayar");
            bayar.requestFocus();
            return;
        }
        
        double uangBayar = Double.parseDouble(bayar.getText());
        
        
        double uangKembali = uangBayar - totalBelanja;
        
        
        if (uangKembali < 0) {
            kembalian.setText("Uang Kurang!");
            kembalian.setForeground(java.awt.Color.RED); // Merah biar warning
            // Matikan tombol bayar biar gabisa simpan
            selesai.setEnabled(false); // Asumsi jButton4 adalah tombol Selesai/Simpan
        } else {
            kembalian.setText("Rp " + String.format("%.0f", uangKembali));
            kembalian.setForeground(java.awt.Color.BLACK);
            
            selesai.setEnabled(true); 
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Input pembayaran harus angka!");
    }
    }//GEN-LAST:event_prosesActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        
        resetForm();
    }//GEN-LAST:event_resetActionPerformed

    private void tambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkanActionPerformed
        // TODO add your handling code here:
        try {
           
            int id = Integer.parseInt(kodeBarang.getText());
            product p = prodCtrl.cariBarang(id);
            int qty = Integer.parseInt(kuantitas.getText());
            
           
            int subtotal = (int) p.getHarga_jual() * qty;
            
           
            model.addRow(new Object[]{
                p.getId_product(),
                p.getNama_product(),
                (int)p.getHarga_jual(),
                qty,
                subtotal
            });
            
            
            totalBelanja += subtotal;
            jLabel7.setText("Rp " + totalBelanja);
            
            
            kodeBarang.setText("");
            namaBarang.setText("");
            kuantitas.setText("");
            kodeBarang.requestFocus();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tambah barang!");
        }
    }//GEN-LAST:event_tambahkanActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        
        try {
       
        model.transaksi t = new model.transaksi();
        
     
        t.setId_transaksi(noTransaksi.getText());
        
      
        java.util.Date tanggalDipilih = tglTransaksi    .getDate();
        
        if (tanggalDipilih == null) { tanggalDipilih = new java.util.Date(); }
        
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        t.setTgl_transaksi(sdf.format(tanggalDipilih)); 
        
        
        t.setId_pegawai(userSession.getId_pegawai());
        
        
        int idCust = 1;
        try {
            idCust = Integer.parseInt(pelanggan.getText());
        } catch (Exception e) {
           
        }
        t.setId_customer(idCust);
        
        
        t.setTotal_belanja(totalBelanja);
        java.util.ArrayList<model.detailTransaksi> listDetail = new java.util.ArrayList<>();
        
        
        for (int i = 0; i < table.getRowCount(); i++) {
            model.detailTransaksi d = new model.detailTransaksi();
            int idProduk = Integer.parseInt(table.getValueAt(i, 0).toString());
            int qty = Integer.parseInt(table.getValueAt(i, 3).toString());
            double subtotal = Double.parseDouble(table.getValueAt(i, 4).toString());
            
            d.setId_product(idProduk);
            d.setQuantity(qty);
            d.setSubtotal((int)subtotal);
            
            
            listDetail.add(d);
        }
        boolean sukses = transCtrl.simpanTransaksi(t, listDetail); 
        
        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this, "Transaksi Berhasil! Kembalian: " + kembalian.getText());
 
            model.setRowCount(0);           
            totalBelanja = 0;               
            jLabel7.setText("0");           
            bayar.setText("");
            kembalian.setText("");
            kodeBarang.setText("");
            namaBarang.setText("");
            kuantitas.setText("");
            
            
            noTransaksi.setText(transCtrl.getNoTransaksiOtomatis());
            
            
            selesai.setEnabled(false);
            
            
            kodeBarang.requestFocus();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Menyimpan ke Database!");
        }
        
    } catch (Exception e) {
        System.out.println("Error Tombol Selesai: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_selesaiActionPerformed

    private void namaKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKasirActionPerformed

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        // TODO add your handling code here:
        new FormLamanInventori().setVisible(true);
    }//GEN-LAST:event_inventoryActionPerformed

    private void generateLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateLaporanActionPerformed
        // TODO add your handling code here:
        new FormLaporan().setVisible(true);
    }//GEN-LAST:event_generateLaporanActionPerformed

    private void akhirHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akhirHariActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(
        this, 
        "Apakah kamu yakin untuk mengakhiri hari ini?",
        "Konfirmasi",
        JOptionPane.OK_CANCEL_OPTION
        );

        if(dialogResult == JOptionPane.OK_OPTION) {
            new FormGuiEndDay().setVisible(true);
        }
    }//GEN-LAST:event_akhirHariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String kodeInput = kodeBarang.getText(); 
    
    if (kodeInput.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Isi Kode Barang dulu!");
        return;
    }

    try {
        
        int id = Integer.parseInt(kodeInput);
        
        
        controller.ProductController prodCtrl = new controller.ProductController(); 
        
        model.product p = prodCtrl.cariBarang(id);
        
        
        if (p != null) {
            
            namaBarang.setText(p.getNama_product());
            
            
            kuantitas.requestFocus(); 
            
        } else {
            
            javax.swing.JOptionPane.showMessageDialog(this, "Barang tidak ditemukan!");
            namaBarang.setText(""); 
            kodeBarang.requestFocus();
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Kode Barang harus berupa angka!");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int barisDipilih = table.getSelectedRow();
    
    if (barisDipilih == -1) {
        
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih barang yang ingin dihapus dari tabel!");
        return;
    }
    
    
    int tanya = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus item ini?", "Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (tanya == javax.swing.JOptionPane.YES_OPTION) {
        try {
            
            double subtotalDihapus = Double.parseDouble(table.getValueAt(barisDipilih, 4).toString());
             
            totalBelanja = (int) (totalBelanja - subtotalDihapus);
            
           
            jLabel7.setText("Rp " + (int)totalBelanja);
            
            
            model.removeRow(barisDipilih);
            kodeBarang.setText("");
            namaBarang.setText("");
            kuantitas.setText("");
            kodeBarang.requestFocus();
            
        } catch (Exception e) {
            System.out.println("Error Hapus: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akhirHari;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton delete;
    private javax.swing.JButton generateLaporan;
    private javax.swing.JButton inventory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kodeBarang;
    private javax.swing.JTextField kuantitas;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JTextField namaKasir;
    private javax.swing.JTextField noTransaksi;
    private javax.swing.JTextField pelanggan;
    private javax.swing.JButton proses;
    private javax.swing.JButton reset;
    private javax.swing.JButton selesai;
    private javax.swing.JTable table;
    private javax.swing.JButton tambahkan;
    private javax.swing.JPanel tanggal;
    private com.toedter.calendar.JDateChooser tglTransaksi;
    // End of variables declaration//GEN-END:variables
}
