/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author putui
 */
public class FormLamanInventori extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLamanInventori.class.getName());

    /**
     * Creates new form FormLamanInventori
     */
    public FormLamanInventori() {
        initComponents();
        // 1. Panggil Controller
    controller.InventoryController inv = new controller.InventoryController();
    
    // 2. Perintahkan untuk mengisi tabel saat aplikasi baru dibuka
    inv.tampilkanData(jTable1);
        this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KodeBarang = new javax.swing.JTextField();
        BtnSimpan = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        BtnKembali = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        NamaBarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Kategori = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        HargaJual = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        HargaBeli = new javax.swing.JTextField();
        BtnCari = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        TambahStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnTambah = new javax.swing.JButton();
        BtnEditJual = new javax.swing.JButton();
        BtnEditBeli = new javax.swing.JButton();
        BtnMultiItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 669));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAMAN INVENTORI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Kode Barang");

        KodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeBarangActionPerformed(evt);
            }
        });

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnKembali.setText("Kembali");
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama Barang");

        NamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBarangActionPerformed(evt);
            }
        });

        jLabel10.setText("Kategori");

        Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriActionPerformed(evt);
            }
        });

        jLabel11.setText("Harga Jual");

        HargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaJualActionPerformed(evt);
            }
        });

        jLabel12.setText("Harga Beli");

        HargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaBeliActionPerformed(evt);
            }
        });

        BtnCari.setText("Cari");
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });

        jLabel13.setText("Tambah Stock");

        TambahStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahStockActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Barang", "Nama Barang", "Harga Beli", "Harga Jual", "Stock", "Supplier"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnEditJual.setText("Edit");
        BtnEditJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditJualActionPerformed(evt);
            }
        });

        BtnEditBeli.setText("Edit");
        BtnEditBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditBeliActionPerformed(evt);
            }
        });

        BtnMultiItem.setText("+");
        BtnMultiItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnSimpan)
                                    .addComponent(BtnReset)
                                    .addComponent(BtnKembali)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(HargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(HargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(30, 30, 30)
                                        .addComponent(KodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnCari)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnMultiItem)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TambahStock, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BtnTambah)
                                    .addComponent(BtnEditJual, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnEditBeli, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 453, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(KodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCari)
                    .addComponent(jLabel13)
                    .addComponent(TambahStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMultiItem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTambah))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(HargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEditJual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(HargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEditBeli))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BtnSimpan)
                .addGap(12, 12, 12)
                .addComponent(BtnReset)
                .addGap(12, 12, 12)
                .addComponent(BtnKembali)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeBarangActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
    // 1. Validasi
    if (KodeBarang.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cari Barang dulu!");
        return;
    }
    
    // Jika kolom tambah stok kosong, anggap 0 (mungkin cuma mau edit harga)
    if (TambahStock.getText().isEmpty()) {
        TambahStock.setText("0");
    }

    try {
        // 2. Ambil Data
        String id = KodeBarang.getText();
        int jumlahTambah = Integer.parseInt(TambahStock.getText());
        int hgBeli = Integer.parseInt(HargaBeli.getText());
        int hgJual = Integer.parseInt(HargaJual.getText());

        // 3. Eksekusi Update
        controller.InventoryController inv = new controller.InventoryController();
        inv.updateStokDanHarga(id, jumlahTambah, hgBeli, hgJual);

        // 4. Refresh Tabel & Reset
        inv.tampilkanData(jTable1); // Pastikan nama tabel di design 'jTable1'
        BtnResetActionPerformed(evt); // Panggil tombol reset
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Harga dan Stok harus angka!");
    }    // TODO add your handling code here:
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void NamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBarangActionPerformed
        Kategori.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_NamaBarangActionPerformed

    private void KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriActionPerformed
        // Saat tekan Enter, pindahkan kursor ke Harga Jual
    // Pastikan nama variabelnya sesuai (HargaJual atau txtHargaJual)
    HargaJual.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_KategoriActionPerformed

    private void HargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaJualActionPerformed
        // Saat tekan Enter, pindahkan kursor ke kolom Harga Beli
    HargaBeli.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_HargaJualActionPerformed

    private void HargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaBeliActionPerformed
        // Saat tekan Enter, pindahkan kursor ke kolom Tambah Stock
    TambahStock.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_HargaBeliActionPerformed

    private void TambahStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahStockActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
// 1. Validasi
    if (KodeBarang.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih barang dulu (Cari)!");
        return;
    }
    
    if (TambahStock.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Isi jumlah stok yang mau ditambah!");
        TambahStock.requestFocus();
        return;
    }

    try {
        String id = KodeBarang.getText();
        int tambahanStok = Integer.parseInt(TambahStock.getText());
        int hgBeli = Integer.parseInt(HargaBeli.getText());
        int hgJual = Integer.parseInt(HargaJual.getText());

        // 2. Update Database
        controller.InventoryController inv = new controller.InventoryController();
        inv.updateStokDanHarga(id, tambahanStok, hgBeli, hgJual);

        // --- FITUR ANTI DUPLIKAT (Supaya Tabel Rapi) ---
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        // Cek satu per satu baris yang ada di tabel
        for (int i = 0; i < model.getRowCount(); i++) {
            String idDiTabel = model.getValueAt(i, 0).toString();
            
            // Jika ketemu ID yang sama...
            if (idDiTabel.equals(id)) {
                model.removeRow(i); // ...Hapus baris lama tersebut!
                break; // Berhenti mencari karena sudah dihapus
            }
        }
        // -----------------------------------------------

        // 3. Masukkan Data Terbaru (Otomatis muncul di paling bawah)
        inv.tambahBarisTabel(jTable1, id);

        // 4. Bersihkan Input Stok
        TambahStock.setText("");
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Kolom Stok/Harga harus angka!");
    
    }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnEditJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditJualActionPerformed
    // Buka kunci hanya untuk Harga Jual
    HargaJual.setEditable(true);
    
    // Langsung arahkan kursor ke sana biar enak ngetik
    HargaJual.requestFocus();
    
    // (Opsional) Beri info kecil
    // javax.swing.JOptionPane.showMessageDialog(this, "Silakan ubah Harga Jual");    // TODO add your handling code here:
    }//GEN-LAST:event_BtnEditJualActionPerformed

    private void BtnEditBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditBeliActionPerformed
    // Buka kunci hanya untuk Harga Beli
    HargaBeli.setEditable(true);
    
    // Arahkan kursor
    HargaBeli.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEditBeliActionPerformed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
    // 1. Ambil ID yang Anda ketik
    String id = KodeBarang.getText(); 
    
    // CEK: Kalau ID kosong, jangan cari (biar ga error)
    if (id.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Isi Kode Barang dulu!");
        return;
    }

    // 2. Panggil Controller
    controller.InventoryController inv = new controller.InventoryController();
    String[] data = inv.cariDetailProduct(id);

    // 3. Cek Hasil Pencarian
    if (data != null) {
        // --- ISI FORM (Data ditemukan) ---
        NamaBarang.setText(data[0]);
        Kategori.setText(data[1]);
        HargaBeli.setText(data[2]);
        HargaJual.setText(data[3]);
        
        // --- BAGIAN KUNCI (Supaya Aman) ---
        // Kunci textfield biar user gak asal edit nama/kategori
        NamaBarang.setEditable(false);
        Kategori.setEditable(false);
        HargaBeli.setEditable(false); 
        HargaJual.setEditable(false);
        
        // Kosongkan HANYA kolom Tambah Stock (Bukan Kode Barang!)
        TambahStock.setText(""); 
        
        // Fokuskan kursor ke Tambah Stock biar enak ngetik
        TambahStock.requestFocus();
        
        // Tampilkan hanya barang ini di tabel
        inv.filterTable(jTable1, id);
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Barang tidak ditemukan!");
        // Jika tidak ketemu, kosongkan nama dkk (Tapi Kode Barang JANGAN dihapus)
        NamaBarang.setText("");
        Kategori.setText("");
        HargaBeli.setText("");
        HargaJual.setText("");
        TambahStock.setText("");
    }
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
    // 1. Bersihkan Textfield
    KodeBarang.setText("");
    NamaBarang.setText("");
    Kategori.setText("");
    HargaBeli.setText("");
    HargaJual.setText("");
    TambahStock.setText("");
    
    // 2. BUKA KUNCI (Supaya bisa ketik Barang Baru) --- [INI YANG PENTING]
    NamaBarang.setEditable(true);
    Kategori.setEditable(true);
    HargaBeli.setEditable(true);
    HargaJual.setEditable(true);
    // ---------------------------------------------------------------------
    
    // 3. Bersihkan Tabel (Sesuai request sebelumnya)
    try {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
    } catch (Exception e) {
    }
    
    // 4. Fokus kembali ke Kode Barang
    KodeBarang.requestFocus();
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void BtnMultiItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiItemActionPerformed
                                             
    // 1. VALIDASI: Pastikan sudah Cari Barang & Isi Stok
    if (KodeBarang.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cari barang dulu sebelum dimasukkan ke tabel!");
        return;
    }
    if (TambahStock.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Isi jumlah stok yang mau ditambah!");
        TambahStock.requestFocus();
        return;
    }

    try {
        // 2. AMBIL DATA DARI FORM
        String id = KodeBarang.getText();
        int tambahanStok = Integer.parseInt(TambahStock.getText());
        int hgBeli = Integer.parseInt(HargaBeli.getText());
        int hgJual = Integer.parseInt(HargaJual.getText());

        // 3. UPDATE DATABASE (Stok Bertambah)
        controller.InventoryController inv = new controller.InventoryController();
        inv.updateStokDanHarga(id, tambahanStok, hgBeli, hgJual);

        // 4. LOGIKA KERANJANG (ANTI DUPLIKAT)
        // Kita cek tabel: Kalau barang ini sudah ada di tabel, hapus baris lamanya.
        // Supaya tidak ada 2 baris "Mouse" yang sama.
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        for (int i = 0; i < model.getRowCount(); i++) {
            String idDiTabel = model.getValueAt(i, 0).toString(); // Ambil ID di kolom pertama
            if (idDiTabel.equals(id)) {
                model.removeRow(i); // Hapus baris lama
                break; // Stop looping karena sudah ketemu
            }
        }

        // 5. MASUKKAN DATA TERBARU (Tempel di Paling Bawah)
        inv.tambahBarisTabel(jTable1, id);

        // 6. BERSIHKAN INPUT (Siap untuk barang selanjutnya)
        TambahStock.setText("");     // Kosongkan stok
        KodeBarang.setText("");      // Kosongkan kode (opsional, biar user tau proses selesai)
        NamaBarang.setText("");      // Bersihkan nama juga biar rapi
        KodeBarang.requestFocus();   // Kursor balik ke Kode Barang (Siap Scan/Ketik lagi)
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Kolom Stok harus angka!");
    }
    }//GEN-LAST:event_BtnMultiItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLamanInventori().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCari;
    private javax.swing.JButton BtnEditBeli;
    private javax.swing.JButton BtnEditJual;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnMultiItem;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JTextField HargaBeli;
    private javax.swing.JTextField HargaJual;
    private javax.swing.JTextField Kategori;
    private javax.swing.JTextField KodeBarang;
    private javax.swing.JTextField NamaBarang;
    private javax.swing.JTextField TambahStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
